-- DigosAR Supabase database
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- It is intentionally separate from the current static frontend.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Public tourism content
-- ---------------------------------------------------------------------------

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null unique,
  icon text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tourist_spots (
  id uuid primary key default gen_random_uuid(),
  category_id bigint references public.categories(id) on delete set null,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null,
  location text not null default 'Digos City',
  short_description text not null,
  about text not null,
  history text,
  cultural_significance text,
  best_time_to_visit text,
  distance_km numeric(7,2) check (distance_km is null or distance_km >= 0),
  latitude numeric(10,7),
  longitude numeric(10,7),
  xp_reward integer not null default 100 check (xp_reward >= 0),
  rating numeric(2,1) not null default 0 check (rating between 0 and 5),
  hero_image_url text,
  ar_model_url text,
  is_ar_supported boolean not null default false,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spot_media (
  id uuid primary key default gen_random_uuid(),
  tourist_spot_id uuid not null references public.tourist_spots(id) on delete cascade,
  media_type text not null check (media_type in ('image', 'video', 'audio', 'model_3d')),
  url text not null,
  thumbnail_url text,
  title text,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (tourist_spot_id, media_type, url)
);

create table if not exists public.spot_facts (
  id uuid primary key default gen_random_uuid(),
  tourist_spot_id uuid not null references public.tourist_spots(id) on delete cascade,
  label text not null,
  value text not null,
  sort_order integer not null default 0,
  unique (tourist_spot_id, label)
);

-- ---------------------------------------------------------------------------
-- Quests and quizzes
-- ---------------------------------------------------------------------------

create table if not exists public.quests (
  id uuid primary key default gen_random_uuid(),
  tourist_spot_id uuid references public.tourist_spots(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  title text not null,
  description text,
  xp_reward integer not null default 150 check (xp_reward >= 0),
  badge_id uuid,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quest_questions (
  id uuid primary key default gen_random_uuid(),
  quest_id uuid not null references public.quests(id) on delete cascade,
  question_text text not null,
  explanation text,
  position integer not null check (position > 0),
  xp_reward integer not null default 50 check (xp_reward >= 0),
  unique (quest_id, position)
);

create table if not exists public.quest_options (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.quest_questions(id) on delete cascade,
  option_text text not null,
  position integer not null check (position > 0),
  is_correct boolean not null default false,
  unique (question_id, position)
);

create unique index if not exists one_correct_option_per_question
  on public.quest_options(question_id)
  where is_correct;

-- ---------------------------------------------------------------------------
-- Users, progress, rewards, and activity
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text, -- Legacy migration field; DigosAR no longer writes or displays it.
  display_name text not null default 'Digos Explorer',
  username text,
  avatar_url text,
  total_xp integer not null default 0 check (total_xp >= 0),
  level integer not null default 1 check (level > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safely migrate existing profiles before enforcing username requirements.
alter table public.profiles add column if not exists username text;

update public.profiles p
set username = case
  when lower(trim(coalesce(u.raw_user_meta_data ->> 'username', ''))) ~ '^[a-z0-9_]{3,20}$'
    then lower(trim(u.raw_user_meta_data ->> 'username'))
  else 'explorer_' || left(replace(p.id::text, '-', ''), 11)
end
from auth.users u
where p.id = u.id
  and (
    p.username is null
    or p.username <> lower(trim(p.username))
    or p.username !~ '^[a-z0-9_]{3,20}$'
  );

update public.profiles
set username = 'explorer_' || left(replace(id::text, '-', ''), 11)
where username is null or username !~ '^[a-z0-9_]{3,20}$';

-- Resolve any legacy case-insensitive duplicates before creating the unique index.
with ranked_usernames as (
  select id, row_number() over (partition by username order by created_at, id) as duplicate_number
  from public.profiles
)
update public.profiles p
set username = 'explorer_' || left(replace(p.id::text, '-', ''), 11)
from ranked_usernames ranked
where p.id = ranked.id and ranked.duplicate_number > 1;

create unique index if not exists profiles_username_key on public.profiles(username);
alter table public.profiles alter column username set not null;
alter table public.profiles drop constraint if exists profiles_username_format;
alter table public.profiles add constraint profiles_username_format
  check (username = lower(trim(username)) and username ~ '^[a-z0-9_]{3,20}$');

create table if not exists public.badges (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null unique,
  description text not null,
  icon text,
  color text,
  xp_required integer not null default 0 check (xp_required >= 0),
  created_at timestamptz not null default now()
);

alter table public.quests
  drop constraint if exists quests_badge_id_fkey;
alter table public.quests
  add constraint quests_badge_id_fkey
  foreign key (badge_id) references public.badges(id) on delete set null;

create table if not exists public.user_badges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_id uuid not null references public.badges(id) on delete cascade,
  earned_at timestamptz not null default now(),
  unique (user_id, badge_id)
);

create table if not exists public.user_spot_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  tourist_spot_id uuid not null references public.tourist_spots(id) on delete cascade,
  status text not null default 'saved' check (status in ('saved', 'visited', 'completed')),
  visit_count integer not null default 0 check (visit_count >= 0),
  first_visited_at timestamptz,
  last_visited_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, tourist_spot_id)
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  tourist_spot_id uuid not null references public.tourist_spots(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, tourist_spot_id)
);

create table if not exists public.ar_scan_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  tourist_spot_id uuid references public.tourist_spots(id) on delete set null,
  recognized boolean not null default false,
  scanned_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  quest_id uuid not null references public.quests(id) on delete cascade,
  score integer not null default 0 check (score >= 0),
  total_questions integer not null default 0 check (total_questions >= 0),
  xp_earned integer not null default 0 check (xp_earned >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.quiz_answers (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references public.quiz_attempts(id) on delete cascade,
  question_id uuid not null references public.quest_questions(id) on delete cascade,
  selected_option_id uuid references public.quest_options(id) on delete set null,
  is_correct boolean not null default false,
  answered_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

create table if not exists public.xp_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  source_type text not null check (source_type in ('spot_visit', 'quest', 'quiz', 'badge', 'admin')),
  source_id uuid,
  description text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists tourist_spots_category_idx on public.tourist_spots(category_id);
create index if not exists tourist_spots_featured_idx on public.tourist_spots(is_featured) where is_published;
create index if not exists tourist_spots_name_search_idx on public.tourist_spots using gin(to_tsvector('english', name || ' ' || short_description));
create index if not exists spot_media_spot_idx on public.spot_media(tourist_spot_id, sort_order);
create index if not exists quest_questions_quest_idx on public.quest_questions(quest_id, position);
create index if not exists quest_options_question_idx on public.quest_options(question_id, position);
create index if not exists user_progress_user_idx on public.user_spot_progress(user_id, status);
create index if not exists quiz_attempts_user_idx on public.quiz_attempts(user_id, completed_at desc);
create index if not exists ar_scan_history_user_idx on public.ar_scan_history(user_id, scanned_at desc);
create index if not exists xp_transactions_user_idx on public.xp_transactions(user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Updated-at triggers
-- ---------------------------------------------------------------------------

drop trigger if exists tourist_spots_set_updated_at on public.tourist_spots;
create trigger tourist_spots_set_updated_at before update on public.tourist_spots
for each row execute function public.set_updated_at();

drop trigger if exists quests_set_updated_at on public.quests;
create trigger quests_set_updated_at before update on public.quests
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_spot_progress_set_updated_at on public.user_spot_progress;
create trigger user_spot_progress_set_updated_at before update on public.user_spot_progress
for each row execute function public.set_updated_at();

-- Automatically create a profile after a Supabase Auth sign-up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    lower(trim(new.raw_user_meta_data ->> 'username')),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', 'Digos Explorer'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.categories enable row level security;
alter table public.tourist_spots enable row level security;
alter table public.spot_media enable row level security;
alter table public.spot_facts enable row level security;
alter table public.quests enable row level security;
alter table public.quest_questions enable row level security;
alter table public.quest_options enable row level security;
alter table public.badges enable row level security;
alter table public.profiles enable row level security;
alter table public.user_badges enable row level security;
alter table public.user_spot_progress enable row level security;
alter table public.favorites enable row level security;
alter table public.ar_scan_history enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.xp_transactions enable row level security;

drop policy if exists "Public categories are readable" on public.categories;
create policy "Public categories are readable" on public.categories for select using (true);

drop policy if exists "Published tourist spots are readable" on public.tourist_spots;
create policy "Published tourist spots are readable" on public.tourist_spots for select using (is_published);

drop policy if exists "Published spot media is readable" on public.spot_media;
create policy "Published spot media is readable" on public.spot_media for select using (
  exists (select 1 from public.tourist_spots s where s.id = tourist_spot_id and s.is_published)
);

drop policy if exists "Published spot facts are readable" on public.spot_facts;
create policy "Published spot facts are readable" on public.spot_facts for select using (
  exists (select 1 from public.tourist_spots s where s.id = tourist_spot_id and s.is_published)
);

drop policy if exists "Published quests are readable" on public.quests;
create policy "Published quests are readable" on public.quests for select using (is_published);

drop policy if exists "Published quest questions are readable" on public.quest_questions;
create policy "Published quest questions are readable" on public.quest_questions for select using (
  exists (select 1 from public.quests q where q.id = quest_id and q.is_published)
);

drop policy if exists "Published quest options are readable" on public.quest_options;
create policy "Published quest options are readable" on public.quest_options for select using (
  exists (
    select 1 from public.quest_questions qq
    join public.quests q on q.id = qq.quest_id
    where qq.id = question_id and q.is_published
  )
);

drop policy if exists "Badges are readable" on public.badges;
create policy "Badges are readable" on public.badges for select using (true);

drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Users may edit only profile presentation fields. XP and level remain server-managed.
revoke update on public.profiles from authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;

drop policy if exists "Users can read their badges" on public.user_badges;
create policy "Users can read their badges" on public.user_badges for select using (auth.uid() = user_id);

drop policy if exists "Users manage their spot progress" on public.user_spot_progress;
create policy "Users manage their spot progress" on public.user_spot_progress for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their favorites" on public.favorites;
create policy "Users manage their favorites" on public.favorites for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their scan history" on public.ar_scan_history;
create policy "Users manage their scan history" on public.ar_scan_history for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their quiz attempts" on public.quiz_attempts;
create policy "Users manage their quiz attempts" on public.quiz_attempts for all
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage answers for their attempts" on public.quiz_answers;
create policy "Users manage answers for their attempts" on public.quiz_answers for all
using (exists (select 1 from public.quiz_attempts a where a.id = attempt_id and a.user_id = auth.uid()))
with check (exists (select 1 from public.quiz_attempts a where a.id = attempt_id and a.user_id = auth.uid()));

drop policy if exists "Users can read their XP history" on public.xp_transactions;
create policy "Users can read their XP history" on public.xp_transactions for select using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Dashboard view
-- ---------------------------------------------------------------------------

create or replace view public.user_dashboard_stats
with (security_invoker = true)
as
select
  p.id as user_id,
  p.display_name,
  p.total_xp,
  p.level,
  count(distinct usp.tourist_spot_id) filter (where usp.status in ('visited', 'completed')) as spots_visited,
  count(distinct qa.id) filter (where qa.completed_at is not null) as quizzes_completed,
  count(distinct ub.badge_id) as badges_earned
from public.profiles p
left join public.user_spot_progress usp on usp.user_id = p.id
left join public.quiz_attempts qa on qa.user_id = p.id
left join public.user_badges ub on ub.user_id = p.id
group by p.id, p.display_name, p.total_xp, p.level;

-- ---------------------------------------------------------------------------
-- Seed data used by the current DigosAR prototype
-- ---------------------------------------------------------------------------

insert into public.categories (slug, name, icon, sort_order) values
  ('nature', 'Nature', 'leaf', 1),
  ('adventure', 'Adventure', 'compass', 2),
  ('culture', 'Culture', 'landmark', 3),
  ('history', 'History', 'history', 4),
  ('highland', 'Highland', 'mountain', 5)
on conflict (slug) do update set name = excluded.name, icon = excluded.icon, sort_order = excluded.sort_order;

insert into public.tourist_spots (
  category_id, slug, name, location, short_description, about, history,
  cultural_significance, best_time_to_visit, distance_km, xp_reward, rating,
  hero_image_url, is_ar_supported, is_featured, is_published
) values
  ((select id from public.categories where slug = 'highland'), 'kapatagan', 'Kapatagan', 'Digos City',
   'A cool highland escape with sweeping mountain views and peaceful farm trails.',
   'Kapatagan is a highland barangay in Digos City known for its cool climate, breathtaking views, and peaceful atmosphere.',
   'Kapatagan grew from a farming community into one of the city''s best-known gateways to the Mount Apo landscape.',
   'Local farms, mountain hospitality, and seasonal produce shape the rhythm of everyday life here.',
   'October – May', 26.00, 100, 4.9, '/touristspot/digos-highlands.webp', true, true, true),
  ((select id from public.categories where slug = 'nature'), 'digos-mother-tree', 'Digos Mother Tree', 'Digos City',
   'A monumental living tree whose vast canopy has become a treasured natural landmark.',
   'The Digos Mother Tree is one of the city''s most recognizable natural landmarks and a place for reflection beneath its expansive canopy.',
   'Generations of residents have gathered beneath its shade, making the tree part of the city''s shared memory.',
   'The landmark represents stewardship, longevity, and the close relationship between Digos and nature.',
   'Year-round', 4.20, 100, 4.8, '/touristspot/digos-mother-tree.webp', true, true, true),
  ((select id from public.categories where slug = 'adventure'), 'mt-apo-view-trail', 'Mt. Apo View Trail', 'Kapatagan',
   'A scenic highland trail with dramatic views toward the country''s highest mountain.',
   'This highland trail offers cool air, mountain scenery, and viewpoints toward the Mount Apo landscape.',
   'The surrounding highlands have long connected communities, farms, and routes toward Mount Apo.',
   'Visitors are encouraged to respect local guides, protected landscapes, and Indigenous traditions.',
   'November – April', 29.00, 100, 4.9, '/touristspot/digos-highlands.webp', true, true, true),
  ((select id from public.categories where slug = 'nature'), 'dawis-beach', 'Dawis Beach', 'Digos City',
   'A laid-back tropical shoreline for sunset walks, sea air, and quiet coastal views.',
   'Dawis Beach offers a simple coastal escape within easy reach of the city.',
   'Dawis reflects the city''s enduring connection to the Davao Gulf and coastal livelihoods.',
   'Simple seaside gatherings and community life give the area its relaxed local character.',
   'December – May', 7.80, 100, 4.6, '/touristspot/dawis-coast.webp', true, true, true)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  location = excluded.location,
  short_description = excluded.short_description,
  about = excluded.about,
  history = excluded.history,
  cultural_significance = excluded.cultural_significance,
  best_time_to_visit = excluded.best_time_to_visit,
  distance_km = excluded.distance_km,
  xp_reward = excluded.xp_reward,
  rating = excluded.rating,
  hero_image_url = excluded.hero_image_url,
  is_ar_supported = excluded.is_ar_supported,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published;

insert into public.spot_facts (tourist_spot_id, label, value, sort_order)
select id, 'Climate', 'Cool highland', 1 from public.tourist_spots where slug = 'kapatagan'
on conflict (tourist_spot_id, label) do update set value = excluded.value, sort_order = excluded.sort_order;

insert into public.spot_facts (tourist_spot_id, label, value, sort_order)
select id, 'Recommended stay', 'Half day', 2 from public.tourist_spots where slug = 'kapatagan'
on conflict (tourist_spot_id, label) do update set value = excluded.value, sort_order = excluded.sort_order;

insert into public.badges (slug, name, description, icon, color, xp_required) values
  ('first-explorer', 'First Explorer', 'Visit your first Digos tourist spot.', 'compass', '#14966A', 0),
  ('ar-explorer', 'AR Explorer', 'Recognize three tourist spots with AR.', 'scan', '#B8FF72', 150),
  ('quiz-master', 'Quiz Master', 'Complete ten tourist quests.', 'trophy', '#F4C542', 500),
  ('digos-explorer', 'Digos Explorer', 'Reach Level 4 in DigosAR.', 'medal', '#0F6B4F', 1000),
  ('highland-scout', 'Highland Scout', 'Complete the Kapatagan Trail quest.', 'mountain', '#78C850', 0)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  color = excluded.color,
  xp_required = excluded.xp_required;

insert into public.quests (tourist_spot_id, slug, title, description, xp_reward, badge_id, is_published)
select s.id, 'kapatagan-trail', 'Kapatagan Trail', 'Learn about Kapatagan''s landscape, climate, and community.', 150, b.id, true
from public.tourist_spots s
cross join public.badges b
where s.slug = 'kapatagan' and b.slug = 'highland-scout'
on conflict (slug) do update set
  tourist_spot_id = excluded.tourist_spot_id,
  title = excluded.title,
  description = excluded.description,
  xp_reward = excluded.xp_reward,
  badge_id = excluded.badge_id,
  is_published = excluded.is_published;

do $$
declare
  quest_uuid uuid;
  q1 uuid;
  q2 uuid;
  q3 uuid;
begin
  select id into quest_uuid from public.quests where slug = 'kapatagan-trail';

  insert into public.quest_questions (quest_id, question_text, explanation, position, xp_reward)
  values (quest_uuid, 'What is Kapatagan known for?', 'Kapatagan is a highland area known for its cool climate and scenery.', 1, 50)
  on conflict (quest_id, position) do update set question_text = excluded.question_text, explanation = excluded.explanation, xp_reward = excluded.xp_reward
  returning id into q1;

  insert into public.quest_questions (quest_id, question_text, explanation, position, xp_reward)
  values (quest_uuid, 'Which major mountain landscape can be viewed from the Kapatagan highlands?', 'The area is a well-known viewpoint and gateway toward Mount Apo.', 2, 50)
  on conflict (quest_id, position) do update set question_text = excluded.question_text, explanation = excluded.explanation, xp_reward = excluded.xp_reward
  returning id into q2;

  insert into public.quest_questions (quest_id, question_text, explanation, position, xp_reward)
  values (quest_uuid, 'What should visitors respect while exploring the highlands?', 'Responsible visitors respect local communities, guides, farms, and protected landscapes.', 3, 50)
  on conflict (quest_id, position) do update set question_text = excluded.question_text, explanation = excluded.explanation, xp_reward = excluded.xp_reward
  returning id into q3;

  insert into public.quest_options (question_id, option_text, position, is_correct) values
    (q1, 'A historical church', 1, false),
    (q1, 'A highland with cool climate', 2, true),
    (q1, 'A white sand beach', 3, false),
    (q1, 'A commercial building', 4, false)
  on conflict (question_id, position) do update set option_text = excluded.option_text, is_correct = excluded.is_correct;

  insert into public.quest_options (question_id, option_text, position, is_correct) values
    (q2, 'Mount Apo', 1, true),
    (q2, 'Mount Pinatubo', 2, false),
    (q2, 'Taal Volcano', 3, false),
    (q2, 'Mayon Volcano', 4, false)
  on conflict (question_id, position) do update set option_text = excluded.option_text, is_correct = excluded.is_correct;

  insert into public.quest_options (question_id, option_text, position, is_correct) values
    (q3, 'Only the photo schedule', 1, false),
    (q3, 'Local communities and protected landscapes', 2, true),
    (q3, 'Shopping center rules', 3, false),
    (q3, 'Airport regulations', 4, false)
  on conflict (question_id, position) do update set option_text = excluded.option_text, is_correct = excluded.is_correct;
end;
$$;

-- ---------------------------------------------------------------------------
-- Supabase Storage buckets
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('spot-media', 'spot-media', true), ('avatars', 'avatars', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can view spot media" on storage.objects;
create policy "Public can view spot media" on storage.objects for select using (bucket_id = 'spot-media');

drop policy if exists "Public can view avatars" on storage.objects;
create policy "Public can view avatars" on storage.objects for select using (bucket_id = 'avatars');

drop policy if exists "Users upload their avatar" on storage.objects;
create policy "Users upload their avatar" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Users update their avatar" on storage.objects;
create policy "Users update their avatar" on storage.objects for update to authenticated
using (bucket_id = 'avatars' and owner_id = auth.uid()::text)
with check (bucket_id = 'avatars' and owner_id = auth.uid()::text);

drop policy if exists "Users delete their avatar" on storage.objects;
create policy "Users delete their avatar" on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and owner_id = auth.uid()::text);

commit;

-- ---------------------------------------------------------------------------
-- Example Supabase queries for the frontend (reference only; not executed)
-- ---------------------------------------------------------------------------
-- Featured spots:
--   supabase.from('tourist_spots').select('*, categories(*)').eq('is_featured', true)
--
-- One spot with media and facts:
--   supabase.from('tourist_spots').select('*, categories(*), spot_media(*), spot_facts(*)').eq('slug', 'kapatagan').single()
--
-- Quest with questions and choices:
--   supabase.from('quests').select('*, quest_questions(*, quest_options(*))').eq('slug', 'kapatagan-trail').single()
--
-- Current user's dashboard:
--   supabase.from('user_dashboard_stats').select('*').single()
--
-- Save a favorite:
--   supabase.from('favorites').insert({ user_id: user.id, tourist_spot_id: spotId })
--
-- Record an AR scan:
--   supabase.from('ar_scan_history').insert({ user_id: user.id, tourist_spot_id: spotId, recognized: true })
